name: Build and Publish to Docker Hub

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create additional environment variables
        run: |
          # get the repo name as lower case
          LGITHUB_REPOSITORY=${GITHUB_REPOSITORY,,}
          # remove 'docker-' from the repo name
          echo "::set-env name=DOCKER_REPOSITORY::${LGITHUB_REPOSITORY//docker-/}"
          # get the tag and remove prefix
          echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF//refs\/tags\//})
      - name: Build and publish container
        uses: elgohr/Publish-Docker-Github-Action@2.13
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: ${{ env.DOCKER_REPOSITORY }}
          tags: "latest,${{ env.RELEASE_VERSION }}"
      - name: Update docker hub description
        uses: peter-evans/dockerhub-description@v2.1.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: ${{ env.DOCKER_REPOSITORY }}
